### ISSUE TITLE
Top Tool Bar - Finding labs and stats page

### ISSUE THREAD

**Issue by lmalhoit** [nre-learning/antidote-web#12]
I see more labs at the top, but I only knew that was there because Matt told me about it a while ago. Otherwise, I probably wouldn’t have explored much to see the other labs (besides the ones with the big buttons in the middle of the page). When I click on each of those, I only get the option of being taken to one lesson. You are probably already working on this.

Also, on the stats page, some of the lab names are overlapping and it’s not totally readable.

**Comment by Mierdin** [comment]
Thanks @lmalhoit - sorry it took so long to follow up on this. We've recently re-vamped the web UI, which includes a lot of improvements that point users to the lesson catalog more easily. So I'll close this. Thanks again!
