### ISSUE TITLE
Inject version into antidote JS files

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-web#3]
This will help ensure people get the upgrades when they come out.

https://stackoverflow.com/questions/32414/how-can-i-force-clients-to-refresh-javascript-files

**Comment by HaykoKoryun** [comment]
I'm working on a solution to append the `hash` of the current `commit` to the end of `antidote.js` in `index.html` at build time, so clients only ever get the latest version if a new image gets deployed.

**Comment by Mierdin** [comment]
Closing in favor of https://github.com/nre-learning/antidote/issues/40
