### ISSUE TITLE
i18n features : multi-language lessons

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-web#74]
I think it could be valuable to think about some support for i18n. Not only would it cover the i18n of the Web interface itself, but also offer some support for translated resources in the curriculum.

I think there are probably tools to ease translation of markdown, and I'm also thinking about changing the locales environment in the running containers.

I'm pretty sure we'd have the need for this in french teaching context where computer science matters are often taught in french... YMMV

**Comment by Mierdin** [comment]
This is a good idea. I have done some **some** i18n work in the past using the Python libraries but it was some time ago. Haven't done anything approaching this for the web. Let me know, if you decide to tackle this, how I can help. I would imagine we would want to tackle the curriculum vs the web front-end in separate initiatives.

**Comment by Mierdin** [comment]
I'm going to close this because the new web UI, with the inclusion of the `antidote-localizations` repository has put us on a solid path to i8n. In the future, when we have multiple translations in that repository, we can open specific PRs for tactical tasks to use them.
