### ISSUE TITLE
User Feedback Box

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-web#76]
Once they've completed a lesson, pop up a quiz, or sends an email for follow-up, to provide feedback for NRE Labs, and ask how it has helped them. Ask for other lesson ideas.

Check this box if we can make your comment public.
Should automatically provide livelesson ID and livesessionID and timestamp (maybe also a field for the user to indicate what time/date they encountered a problem. Both will help with log correlation).
Maybe optionally display this to the user if they ask for it (maybe a button that shows "debug info" in this feedback box)

Should also provide a feedback button on the lesson so they can provide this any time, not just at the "end".

Ensure all session state is transmitted so we can follow up with them if there were issues. (maybe also a field for the user to indicate what time/date they encountered a problem. Both will help with identifying any issues later)

**Comment by natzberg** [comment]
Where would the feedback be sent to for this? I've got a generic modal up, but I'm not sure where the submit should point to.

**Comment by Mierdin** [comment]
I haven't thought deeply about back-ends yet. Any ideas? Ideally would be something fairly open-source friendly, as well as something with basic anti-spam as well as triaging capabilities.

**Comment by natzberg** [comment]
Is there an email account associated with NRE Labs? Perhaps there could be a specific email for feedback, like a gmail account. However I don't know how that would work for giving developers access to the email.

I'd have to look into what can be done on the front-end for spam, but I think you could also set the email settings to be strict on spam or something.

Otherwise I'm not sure at the moment...

**Comment by Mierdin** [comment]
I'll be taking this on shortly - found a way to pre-populate a disqus forum post with this information:

```
http://discuss.nrelabs.io/new-topic?title=topictitle&body=topicbody&category=nre-labs-curriculum&tags=nrelabsform
```

We're already using disqus for the user forums so this should work well, and won't require us to maintain a separate backend for these requests.

This will need to get embedded into a button or link present in the main lesson interface, as well as an option for error modals.
