### ISSUE TITLE
Paste not working in FF

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-web#79]
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#Browser_compatibility

```
TypeError: navigator.clipboard.readText is not a function[Learn More] antidote.js:524:5
    paste https://ptr.labs.networkreliability.engineering/js/antidote.js?cd09e0311bcbceca150bcfd01473a7180ef4477f:524
    onclick https://ptr.labs.networkreliability.engineering/labs/?lessonId=35&lessonStage=1:1
```

It appears this was always the case. We should come up with a more robust, cross-browser way of pasting into the terminal. We should also probably take the opportunity to make use of keyboard shortcuts instead of buttons in the UI.

**Comment by natzberg** [comment]
I looked into this and it seems like you either have to add `clipboardWrite` and `clipboardRead` permissions to the manifest file, or just use `document.execCommand('paste')`.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Clipboard_access

**Comment by natzberg** [comment]
The clipboard API seems to be broken as a whole at the moment. Firefox doesn't recognize clipboardWrite/clipboardRead or clipboard-write/clipboard-read as valid permissions even in just the console. I'm going to try using `document.execCommand('paste').

So as long as the user is copying from within the tabs, it will work. However it will not work if you copy from outside the tabs unfortunately.

Seems like this is a known issue Mozilla has chosen not to fix yet. https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
`Note: At this time, while Firefox does implement read(), it does not recognize the "clipboard-read" permission, so attempting to use the Permissions API to manage access to the API will not work.`

**Comment by Mierdin** [comment]
@natzberg Heads up, the re-vamp efforts that finished a few months back seem to have addressed this. So I'm going to close this. Thanks so much for the discovery efforts above.
