### ISSUE TITLE
open twitter links for contributors in new tab

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote-web#80]
The links for contributors' user handles that go to Twitter are opening in the same window/tab. Please add a target="_blank" so they open somewhere new and don't disrupt the lesson flow. Thanks

**Comment by Mierdin** [comment]
Ah - probably because these are still part of the curriculum, so there's not a platform-level standard for handling this. The upcoming "guest book" concept for author attribution should help with this.

**Comment by Mierdin** [comment]
Finally had a chance to implement this in https://github.com/nre-learning/antidote-ui-components/pull/17, which brings this functionality out of the curriculum and into the platform. Links are always opened in a new tab.
