### ISSUE TITLE
Avoid tracking the user on Youtube from the frontpage

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-web#83]
Even if one doesn't open the "watch intro video", there's a ton of queries done on YouTube... which ain't really cool, tracking-wise :-/

Maybe this should be on a separate page, or embedded in a way that doesn't query YT at each access to the homepage...

**Comment by Mierdin** [comment]
This will be addressed in https://github.com/nre-learning/antidote-web/pull/85
