### ISSUE TITLE
Force use of Python 3 for templates generation with Jinja

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-web#98]
The templates target rebuild in the Makefile involves Python 2.7, which is deprecated now.

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Not a big deal, but worth addressing some day

**Comment by olberger** [comment]
Uh... actually, this seems to be on my side ;-)

Maybe there's a way to ensure that use of a recent Python version is enforceable ?

**Comment by Mierdin** [comment]
I don't think enforcing the use of a specific version of Python is in scope here. I use Python3, if someone tries using something else, YMMV.

```
~$ venv/bin/python --version
Python 3.6.7
```
